services:
  - type: web
    name: leaf-health-detector
    env: python
    region: oregon          
    plan: free             
    buildCommand: pip install -r requirements.txt
    startCommand: python host.py
